name: hydronet
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python==3.*
  - tensorflow-gpu==2.2.*
  - ase==3.19.*
  - pytorch>=1
  - networkx==2.4.*
  - pandas==0.25.*
  - scikit-learn==0.22.*
  - scipy>=0.11.0
  - tqdm
  - tabulate
  - jupyterlab
  - matplotlib
  - pytest
  - pip
  - pip:
      - globus-cli
      - schnetpack
      - tf-agents==0.8.*
      - tensorflow_probability==0.12.2
      - -e .  # The graphsage libraries in development mode
