# Environment that uses CPU version of TF and PyTorch
name: hydronet
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9.*
  - ase==3.19.*
  - networkx==2.7.*
  - pandas==0.25.*
  - scikit-learn==1.*
  - mongodb==5.*
  - pydantic
  - pymongo
  - tqdm
  - tabulate
  - jupyterlab
  - matplotlib
  - pytest
  - pip
  - pip:
      - torch==1.9.0+cpu
      - intel-tensorflow==2.6.*
      - globus-cli
      - schnetpack
      - tf-agents==0.8.*
      - gym
      - -e .  # The graphsage libraries in development mode
      - -f https://download.pytorch.org/whl/torch_stable.html
