name: hydronet
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.*
  - tensorflow-gpu==2.2.*
  - ase==3.19.*
  - networkx==2.4.*
  - pandas==0.25.*
  - scikit-learn==0.22.*
  - tqdm
  - jupyterlab
  - matplotlib
  - pytest
  - pip
  - pip:
      - globus-cli
      - -e .  # The graphsage libraries in development mode
