# Environment that uses a locally-installed CUDA 11.x library
name: hydronet
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9.*
  - ase==3.19.*
  - networkx==2.7.*
  - pandas==1.*
  - scikit-learn==1.*
  - mongodb==5.*
  - pymongo
  - pydantic
  - tqdm
  - tabulate
  - jupyterlab
  - matplotlib
  - pytest
  - pip
  - pip:
      - tensorflow==2.6.*
      - torch==1.9.0+cu111
      - globus-cli
      - schnetpack
      - tf-agents==0.8.*
      - gym
      - -e ..  # The graphsage libraries in development mode
      - -f https://download.pytorch.org/whl/torch_stable.html
